name: drugdesign
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - pip
  - pytorch=2.5
  - pip:
      - poetry
